accounts/urls.py
#accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='password'),
    path('<str:username>/delete/', views.delete, name='delete'),
]

chats/urls.py
from django.urls import path
from . import views

app_name = 'chats'
urlpatterns = [
    path('inbox/', views.inbox, name='inbox'),
    path('<int:user_id>/', views.start_chat, name='start_chat'),
    path('start_group_chat/', views.start_group_chat, name='start_group_chat'),
    path('<str:room_name>/', views.room, name='room'),
    path('<str:room_name>/delete/', views.delete_chat, name='delete_chat'),
    path('api/unread_notifications/', views.unread_notifications, name='unread_notifications'),
    path('api/new_chat_rooms/', views.get_new_chat_rooms, name='new_chat_rooms'),
]

config/urls.py
#config/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # post
    path('', views.index, name='index'),
    # path('posts/hobby/', views.hobby, name='hobby'),
    path('posts/<int:post_pk>/', views.post_detail, name='post_detail'),
    path('posts/create/', views.post_create, name='post_create'),
    path('posts/<int:post_pk>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_pk>/update/', views.post_update, name='post_update'),
    path('posts/<int:post_pk>/comments/', views.post_comments_create, name='post_comments_create'),
    path('posts/<int:post_pk>/comments/<int:comment_pk>/delete', views.post_comments_delete, name='post_comments_delete'),
    # path('posts/<int:post_pk>/comments/<int:comment_pk>/update', views.post_comments_update, name='post_comments_update'),
    path('posts/<int:post_pk>/post_likes/', views.post_likes, name='post_likes'),
    path('posts/where', views.where, name='where'),

    # group
    path('posts/group/', views.group_list, name='group_list'),
    path('posts/group/<int:group_pk>/', views.group_detail, name='group_detail'),
    path('posts/group/create/', views.group_create, name='group_create'),
    path('posts/group/<int:group_pk>/update/', views.group_update, name='group_update'),
    path('posts/group/<int:group_pk>/delete/', views.group_delete, name='group_delete'),
    path('posts/group/<int:group_pk>/comments/', views.group_comments_create, name='group_comments_create'),
    path('posts/group/<int:group_pk>/comments/<int:comment_pk>/delete', views.group_comments_delete, name='group_comments_delete'),
    # path('posts/group/<int:group_pk>/comments/<int:comment_pk>/update/', views.group_comments_update, name='group_comments_update'),
    path('posts/group/<int:group_pk>/group_likes/', views.group_likes, name='group_likes'),

    # 기타
    path('posts/search/', views.search, name='search'),
    path('posts/category/<str:subject>/', views.category, name='category'),
    # path('posts/guide/', views.guide, name='guide'),
]   

accounts/models.py
#accounts/models.py

from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings
from posts.models import Group

# Create your models here.
class User(AbstractUser):
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=30)
    joined_at = models.DateTimeField(auto_now_add=True)
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    level = models.IntegerField(default=1)
    profile_image = ProcessedImageField(blank=True,
                                        upload_to='users',
                                        processors=[ResizeToFill(200, 200)],
                                        format='JPEG',
                                        options={'quality': 70})
    
    def image_path(instance, filename):
        return f'account/{instance.pk}/{filename}'
    
    def liked_groups(self):
        return Group.objects.filter(like_users=self)
    

accounts/forms.py
# accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UsernameField

# 로그인
class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label = '아이디',
        widget = forms.TextInput(
            attrs = {}
        )
    )

    password = forms.CharField(
        label = '비밀번호',
        widget = forms.PasswordInput(
            attrs = {}
        )
    )

# 회원가입
class CustomUserCreationForm(UserCreationForm):
    name = forms.CharField(label='이름*', widget=forms.TextInput(attrs={'placeholder': ' '}))
    email = forms.EmailField(
        label='이메일',
        required=False,
        widget=forms.EmailInput(attrs={'placeholder': ' '})
        )
    password1 = forms.CharField(
        label='비밀번호*', 
        widget=forms.PasswordInput(attrs={'placeholder' : ' '}),
        help_text=None,
        )
    password2 = forms.CharField(
        label='비밀번호 확인*', 
        widget=forms.PasswordInput(attrs={'placeholder' : ' '}),
        )
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'name', 'email')
        labels = {
            'username': '아이디*',
        }
        widgets = {
            'username': forms.TextInput(attrs={'placeholder' : ' '}),
        }
        help_texts = {
            'username': None,
        }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if username and get_user_model().objects.filter(username=username).exists():
            raise ValidationError('중복된 아이디입니다.')
        return username

# 회원정보 변경
class CustomUserChangeForm(UserChangeForm):
    password = None
    name = forms.CharField(
        required=False,
        label='이름',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이름'
            }
        )
    )
    
    email = forms.EmailField(
        required=False,
        label='이메일',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이메일',
            }
        )
    )

    profile_image = forms.ImageField(
        required=False,
        label='프로필 이미지',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control',
                'placeholder': '프로필 이미지'
            }
        )
    )
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'name', 'profile_image')


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='현재 비밀번호*', 
        widget=forms.PasswordInput(attrs={})
        )
    new_password1 = forms.CharField(
        label='새로운 비밀번호*', 
        widget=forms.PasswordInput(attrs={})
        )
    new_password2 = forms.CharField(
        label='새로운 비밀번호 확인*', 
        widget=forms.PasswordInput(attrs={})
        )
    
    class Meta:
        model = get_user_model()
        fields = '__all__'

accounts/views.py
# account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout, get_user_model, update_session_auth_hash
from django.http import JsonResponse
from .forms import CustomAuthenticationForm, CustomUserCreationForm, CustomUserChangeForm, CustomPasswordChangeForm
from posts.models import Group, GroupComment, PostComment
# from django.db.models import Count

def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('posts:index')
            else:
                form.add_error(None, '아이디와 비밀번호를 확인해 주세요')
    else:
        form = CustomAuthenticationForm(request)

    return render(request, 'accounts/login.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    
    return render(request, 'accounts/signup.html', {'form': form})

def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('posts:index')

@login_required
def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    post_comments = person.postcomment_set.count()
    groups = person.group_set.all().order_by('-created_at')
    group_comments = person.groupcomment_set.count()

    liked_groups = person.liked_groups()
    liked_posts = person.like_posts.all()

    score = groups.count() * 50 + post_comments * 5 + group_comments * 5

    if score < 200:
        level = 1
        min_score = 0
        max_score = 200
        need_score = 200
    elif score < 400:
        level = 2
        min_score = 200
        max_score = 400
        need_score = 200
    elif score < 600:
        level = 3
        min_score = 400
        max_score = 600
        need_score = 200
    elif score < 800:
        level = 4
        min_score = 600
        max_score = 800
        need_score = 200
    elif score >= 1000:
        level = 5
        min_score = 800
        max_score = 'MAX'
        need_score = 200

    if max_score == 'MAX':
        expbar = 100
        restexp = 0
    else:
        now_score = score - min_score
        expbar = (now_score / need_score) * 100
        restexp = need_score - now_score

    if person.level != level:
        person.level = level
        person.save()

    level_dict = {1: '뉴비', 2: '초보', 3: '중수', 4: '고수', 5: '마스터'}

    context = {
        'person': person,
        'groups': groups, 
        'level_name': level_dict[level],
        'max_score': max_score,
        'liked_posts': liked_posts,
        'liked_groups' : liked_groups,
        'score': score,
        'expbar': expbar,
        'restexp': restexp,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, user_pk):
    User = get_user_model()
    you = User.objects.get(pk=user_pk)
    me = request.user

    if you != me:
        if me in you.followers.all():
            you.followers.remove(me)
            is_followed = False
        else:
            you.followers.add(me)
            is_followed = True

        context = {
            'is_followed': is_followed,
            'followings_count': you.followings.count(),
            'followers_count': you.followers.count(),
        }

        return JsonResponse(context)

    return redirect('accounts:profile', you.username)

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', username=request.user.username)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  
            return redirect('accounts:profile', username=request.user.username)
    else:
        form = CustomPasswordChangeForm(user=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/password.html', context)


@login_required
def delete(request, username):
    person = get_user_model().objects.get(username=username)
    if request.user == person:
        person.delete()
        auth_logout(request)
        
    return redirect('posts:index')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class='container text-center'>
  <h3 class='border-bottom border-dark mx-auto my-5' style='width : 200px;'>HOBBY HUB</h3>

  <form method="post">
    {% csrf_token %}
    <div class="form-floating mx-auto mb-3" style="width : 250px;">
      <input type="text" class="form-control" name="username" id="floatingInput" placeholder=" ">
      <label for="floatingInput">아이디</label>
    </div>
    <div class="form-floating mx-auto mb-3" style="width : 250px;">
      <input type="password" class="form-control" name="password" id="floatingPassword" placeholder=" ">
      <label for="floatingPassword">비밀번호</label>
    </div>
    <div class='mb-4'>
      <button class="btn btn-outline-success" type="submit">로그인</button>        
    </div>    
  </form>

  <div class='d-flex justify-content-center'>
    {% load socialaccount %}
    <a href="{% provider_login_url 'naver'%}">
      <img class='me-3' src="{% static 'img/994331335F52047D05.png' %}" width=40px>
    </a> <br>
    <a href="{% provider_login_url 'google' %}">
      <img src="{% static 'img/google_logo_2_littledeep.png' %}" width=38px>
    </a> 
  </div>
  

  <br>
  <p class='my-1'>아직 계정이 없으신가요?</p>
  <a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover text-primary-emphasis-hover" href="{% url 'accounts:signup' %}">
    회원가입      
  </a>
</div>
{% endblock %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet" href="{% static 'css/update.css' %}">
{% endblock link %}

{% block content %}
<div class='text-center mx-auto my-5 update__form' style='width: 300px;'>
  <form id="passwordChangeForm" method="post">
     {% csrf_token %}
 
     <p>
       <label for="id_old_password">현재 비밀번호*:</label>
       <input type="password" name="old_password" id="id_old_password" required>
     </p>
     
     <p>
       <label for="id_new_password1">새로운 비밀번호*:</label>
       <input type="password" name="new_password1" id="id_new_password1" required>
     </p>
     
     <p>
       <label for="id_new_password2">새로운 비밀번호 확인*:</label>
       <input type="password" name="new_password2" id="id_new_password2" required>
     </p>    
     
     <button type="submit" class="btn btn-primary">저장</button>
   </form>
 
   <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class="modal-dialog">
       <div class="modal-content">
         <div class="modal-header"></div>
         <div class="modal-body">
           저장되었습니다
         </div>
         <div class="modal-footer">
           <a class="btn btn-secondary" href="{% url 'accounts:profile' request.user.username %}">확인</a>
         </div>
       </div>
     </div>
   </div>
 </div>
 
{% endblock content %}

{% block script %}
<script src="{% static 'js/password.js' %}"></script>
{% endblock script %}

accounts/templates/accounts/profile.html
<!-- accounts/templates/accounts/prorile.html -->
{% extends 'base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet" href="{% static 'css/level.css' %}">
{% endblock link %}

{% block content %}
  <div class="container d-flex justify-content-between p-0 mt-5">
    
    <!-- 왼쪽영역 -->
    <div class="left_field col-4">
      <!-- 유저정보 영역 -->
      <div class="user_box text-center">
          <!-- 이미지 -->
          <div class="profile_img mt-4 mb-4">
            {% if person.profile_image %}
                <img class="rounded-circle" src="{{ person.profile_image.url }}" width="150px" alt="Profile Image">
            {% else %}
                <img class="rounded-circle" src="https://i.postimg.cc/kXwSg0M2/image.jpg" width="150px" alt="Default Profile Image">
            {% endif %}
          </div>
          <!-- 프로필 -->
          <div class="user_info">
            <h2 class="user-name fw-bold">{{ person.username }}</h2>
            <div class="social_icon d-flex justify-content-center">
              {% if user.email %}
              <a class='text-dark' href="javascript:void(0)" onclick="copyToClipboard('{{ user.email }}')">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                  <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/>
                </svg>
              </a>

            {% endif %}
          </div>
          <div>
            {% if person.level == 1 %}
              <div class="d-flex flex-row">
                <img class="levelname--img" src="{% static '' %}" alt=""><p class="levelname">뉴비</p>
              </div>
            {% elif person.level == 2 %}
              <div class="d-flex flex-row">
                <img class="levelname--img" src="{% static '' %}" alt=""><p class="levelname">초보</p>
              </div>
            {% elif person.level == 3 %}
            <div class="d-flex flex-row">
              <img class="levelname--img" src="{% static '' %}" alt=""><p class="levelname">중수</p>
            </div>
            {% elif person.level == 4 %}
            <div class="d-flex flex-row">
              <img class="levelname--img" src="{% static '' %}" alt=""><p class="levelname">고수</p>
            </div>
            {% elif person.level == 5 %}
            <div class="d-flex flex-row">
              <img class="levelname--img" src="{% static '' %}" alt=""><p class="level5name">마스터</p>
            </div>
            {% endif %}
          </div>
          <div class="progress profile__user--expbar" role="progressbar" aria-label="Example with label" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" title="다음 레벨까지 {{ restexp }}점 남았습니다.">
            <div class="progress-bar bg-success" style="width: {{ expbar }}%"></div>
            <p class="profile__user--expcount">
              {% if max_score == 'MAX' %}
                {{ max_score }}
              {% else %}
                {{ score }}/{{ max_score }}
              {% endif %}
            </p>
          </div>
          <div class="follow_box">
            <div class="d-flex justify-content-center align-items-center">
            <!-- 팔로워/팔로잉 수 -->              
              <p class="user-follow-text m-0">팔로잉</p>
              <button type="button" id="followings-count" class="btn" data-bs-toggle="modal" data-bs-target="#followingModal">{{ person.followings.all|length }}</button>
              <p class="user-follow-text m-0">팔로워</p>
              <button type="button" id="followers-count" class="btn" data-bs-toggle="modal" data-bs-target="#followerModal">{{ person.followers.count }}</button>
            </div>
          </div>
          <!-- 팔로잉 모달 -->
          <div class="modal fade" id="followingModal" tabindex="-1" aria-labelledby="followingModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="followingModalLabel">팔로잉 목록</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  {% for follower in person.followings.all %}
                  <div class="d-flex justify-content-between mb-2">
                    <a class='text-dark link-underline link-underline-opacity-0' href="{% url 'accounts:profile' follower %}" class="d-flex">
                      {% if person.profile_image %}
                          <img class="rounded-circle" src="{{ person.profile_image.url }}" width="50px" alt="Profile Image">
                      {% else %}
                          <img class="rounded-circle" src="https://i.postimg.cc/kXwSg0M2/image.jpg" width="50px" alt="Default Profile Image">
                      {% endif %}
                      {{ follower }}
                    </a>
                  </div>
                {% endfor %}
                </div>
              </div>
            </div>
          </div>
          <!-- 팔로워 모달 -->
          <div class="modal fade" id="followerModal" tabindex="-1" aria-labelledby="followerModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="followerModalLabel">팔로워 목록</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  {% for follower in person.followers.all %}
                    <div class="d-flex justify-content-between mb-2">
                      <a class='text-dark link-underline link-underline-opacity-0' href="{% url 'accounts:profile' follower %}" class="d-flex">
                        {% if person.profile_image %}
                            <img class="rounded-circle" src="{{ person.profile_image.url }}" width="50px" alt="Profile Image">
                        {% else %}
                            <img class="rounded-circle" src="https://i.postimg.cc/kXwSg0M2/image.jpg" width="50px" alt="Default Profile Image">
                        {% endif %}
                        {{ follower }}
                      </a>
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
        
          <!-- 로그인+본인 프로필이어야 노출되는 부분 -->
          <div class="Enable Login my-3">
            {% if user == person %}
              <div class="profile_update">
                <a href="{% url 'accounts:update' %}">
                  <button class="btn btn-outline-dark" style="width: 144px;">프로필 업데이트</button>
                </a>
              </div>
              <div class="change_password">
                <a href="{% url 'accounts:password' %}">
                  <button class="btn btn-outline-dark mt-2" style="width: 144px;">비밀번호 변경</button>
                </a>
              </div>
              <div class='small'>
                <br>
                <br>
                <br>
                <br>
                <a class='ms-1 px-1' href="{% url 'accounts:delete' username=user.username %}">
                  <button type="submit" class="link-underline link-underline-opacity-0 btn btn-link text-danger m-1 p-0" onclick="return confirm('정말 탈퇴하시겠습니까?')">
                    <p class="text-body-tertiary">              
                      회원탈퇴
                    </p>
                  </button> 
                </a>
              </div>
            {% else %}          
              <div class="follow-btn">
                <form id="follow-form" data-user-id="{{ person.pk }}">
                  {% csrf_token %}
                  {% if request.user in person.followers.all %}
                    <input type="submit" value="언팔로우" class="btn btn-dark fw-bold">
                  {% else %}
                    <input type="submit" value="팔로우" class="btn btn-outline-dark fw-bold {% if not user.is_authenticated %}disabled{% endif %}">
                  {% endif %}
                </form>
              </div>
            {% endif %}
            </div>
          </div>
      </div>
    </div>

    <!-- 오른쪽영역 -->
    <div class="right_field col-8 my-4">
      <div>
        <h4 class='text-center mb-4'>{{ person.username }} 님이 좋아하는 취미</h4>
        <div class='align-items-center d-flex border rounded' style="height: 300px;">
          <div class='flex-column w-100'>
            <ul class="list-unstyled my-2">
              {% for post in liked_posts|slice:":4" %}
                <div class="ms-5 mb-2">
                  <a class="link-underline link-underline-opacity-0 text-dark" href="{% url 'posts:post_detail' post_pk=post.pk %}">
                    <li class="list-group-item">{{ post.title }}</li>
                  </a>
                  <hr class='text-start mt-1' style='width: 200px;'>     
                </div>                
              {% empty %}
                <li><div class='text-center'>아직 좋아요 한 취미가 없습니다</div></li>
                <br>
                <br>
              {% endfor %}
            </ul>
            <br>          
            <div class='text-center'>
              <a href="{% url 'posts:index' %}">
                <button class="btn btn-outline-dark">취미 찾으러 가기</button>
              </a>
            </div>
          </div>        
        </div>
      </div>  
      <br>
      <div class='my-4'>
        <h4 class='text-center mb-4'>{{ person.username }} 님이 좋아하는 그룹</h4>
        <div class='align-items-center d-flex border rounded' style="height: 300px;">
          <div class='flex-column w-100'>
            <ul class="list-unstyled my-2">
              {% for group in liked_groups|slice:":4" %}
                <div class='ms-5 mb-2'>
                  <a class="link-underline link-underline-opacity-0 text-dark" href="{% url 'posts:group_detail' group_pk=group.pk %}">
                    <li>{{ group.title }}</li>
                  </a>
                  <hr class='text-start mt-1' style='width: 200px;'>                
                </div>            
              {% empty %}
                <li><div class='text-center'>아직 좋아요 한 그룹이  없습니다.</div></li>
                <br>
                <br>
              {% endfor %}
            </ul>
            <br>          
            <div class='text-center'>
              <a href=" {% url 'posts:where' %} ">
                <button class="btn btn-outline-dark">내 주변 모임 찾아보기</button>
              </a> 
            </div>
          </div>        
        </div>
      </div>
    </div>
    
  </div>
{% endblock content %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="{% static 'js/profile.js' %}"></script>
  <script>
    function copyToClipboard(text) {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document
        .body
        .appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document
        .body
        .removeChild(textarea);

      const notification = document.createElement('div');
      notification.innerText = '이메일 주소가 복사되었습니다.';
      notification.style.position = 'fixed';
      notification.style.bottom = '10px';
      notification.style.left = '50%';
      notification.style.transform = 'translateX(-50%)';
      notification.style.background = '#f2f2f2';
      notification.style.padding = '10px';
      notification.style.borderRadius = '5px';
      notification.style.boxShadow = '0 2px 5px rgba(0, 0, 0, 0.2)';

      document
        .body
        .appendChild(notification);
      setTimeout(function () {
        document
          .body
          .removeChild(notification);
      }, 3000);
    }
  </script>
{% endblock script %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock link %}

{% block content %}
<div class='signup-page'>
  <div class='signup-page__title'>
    <h3>HOBBY HUB</h3>
    <h4>Sign up</h4>
  </div>
  <form method="post" class='signup-page__form'>
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">등록</button>
  </form>
</div>

{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
  <link rel="stylesheet" href="{% static 'css/update.css' %}">
{% endblock link %}

{% block content %}
<div class='text-center mx-auto my-5 update__form' style='width: 300px;'>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_email">이메일</label>
      <input type="email" class="form-control" id="id_email" name="email" placeholder="이메일" 
      {% if value %}
      value="{{ form.email.value }}"
      {% else %}
      value=""
      {% endif %}>
    </div>
    <div class="form-group">
    <label for="id_name">이름</label>
    <input type="text" class="form-control" id="id_name" name="name" placeholder="이름" 
    {% if value %}
    value="{{ form.name.value }}"
    {% else %}
    value=""
    {% endif %}
    >
    </div>    
    <div class="form-group">
      <label for="id_profile_image">프로필 이미지</label>
      <input type="file" class="form-control-file" id="id_profile_image" name="profile_image" placeholder="프로필 이미지">
    </div>
    
    <button type="submit" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">저장</button>
  </form>
 
   <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class="modal-dialog">
       <div class="modal-content">
         <div class="modal-header"></div>
         <div class="modal-body">
           저장되었습니다
         </div>
         <div class="modal-footer">
           <a class="btn btn-secondary" href="{% url 'accounts:profile' request.user.username %}">확인</a>
         </div>
       </div>
     </div>
   </div>
 </div>
 
{% endblock content %}

{% block script %}
<script src="{% static 'js/update.js' %}"></script>
{% endblock script %}