accounts/urls.py
#accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='password'),
    path('<str:username>/delete/', views.delete, name='delete'),
]

chats/urls.py
from django.urls import path
from . import views

app_name = 'chats'
urlpatterns = [
    path('inbox/', views.inbox, name='inbox'),
    path('<int:user_id>/', views.start_chat, name='start_chat'),
    path('start_group_chat/', views.start_group_chat, name='start_group_chat'),
    path('<str:room_name>/', views.room, name='room'),
    path('<str:room_name>/delete/', views.delete_chat, name='delete_chat'),
    path('api/unread_notifications/', views.unread_notifications, name='unread_notifications'),
    path('api/new_chat_rooms/', views.get_new_chat_rooms, name='new_chat_rooms'),
]

config/urls.py
#config/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # post
    path('', views.index, name='index'),
    # path('posts/hobby/', views.hobby, name='hobby'),
    path('posts/<int:post_pk>/', views.post_detail, name='post_detail'),
    path('posts/create/', views.post_create, name='post_create'),
    path('posts/<int:post_pk>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_pk>/update/', views.post_update, name='post_update'),
    path('posts/<int:post_pk>/comments/', views.post_comments_create, name='post_comments_create'),
    path('posts/<int:post_pk>/comments/<int:comment_pk>/delete', views.post_comments_delete, name='post_comments_delete'),
    # path('posts/<int:post_pk>/comments/<int:comment_pk>/update', views.post_comments_update, name='post_comments_update'),
    path('posts/<int:post_pk>/post_likes/', views.post_likes, name='post_likes'),
    path('posts/where', views.where, name='where'),

    # group
    path('posts/group/', views.group_list, name='group_list'),
    path('posts/group/<int:group_pk>/', views.group_detail, name='group_detail'),
    path('posts/group/create/', views.group_create, name='group_create'),
    path('posts/group/<int:group_pk>/update/', views.group_update, name='group_update'),
    path('posts/group/<int:group_pk>/delete/', views.group_delete, name='group_delete'),
    path('posts/group/<int:group_pk>/comments/', views.group_comments_create, name='group_comments_create'),
    path('posts/group/<int:group_pk>/comments/<int:comment_pk>/delete', views.group_comments_delete, name='group_comments_delete'),
    # path('posts/group/<int:group_pk>/comments/<int:comment_pk>/update/', views.group_comments_update, name='group_comments_update'),
    path('posts/group/<int:group_pk>/group_likes/', views.group_likes, name='group_likes'),

    # 기타
    path('posts/search/', views.search, name='search'),
    path('posts/category/<str:subject>/', views.category, name='category'),
    # path('posts/guide/', views.guide, name='guide'),
]   

templates/banner.html
{% load static %} 

{% block title %}{% endblock title %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/banner.css' %}" />
{% endblock head %}
{% block content %}
{% comment %} <!-- 케로젤 배너1 -->
<div class="c1-banner">
  <div class="c-banner1">
    <div>
      <p class="c-t1">STUDY</p>
      <p class="c-t2">글쓰기는 자기 발견과 성장의 기회입니다.</p>
      <p class="c-t2">매일 조금씩 나아지는 모습이 나의 진정한 성공입니다.</p>
    </div>
    <img src="https://www.nicetomeetme.kr/images/main/store_icon.png" alt="배너" class="c-banner-img">
  </div>
</div>

<!-- 케로젤 배너2 -->
<div class="c2-banner">
  <div class="c-banner1">
    <div>
      <p class="c-t1">ACTIVITY</p>
      <p class="c-t2">스포츠는 몸과 마음을 강화하는 길입니다.</p>
      <p class="c-t2">운동은 스트레스를 해소하고 자신감을 키우는 방법입니다.</p>
    </div>
    <img src="https://cdn-icons-png.flaticon.com/512/901/901788.png?w=1060&t=st=1686644544~exp=1686645144~hmac=2fe3408d80af5f22a259548b6d3e7056237fa3f735e1cf3fd42bd40f78e5c687" alt="배너" class="c-banner-img">
  </div>
</div>

<!-- 케로젤 배너3 -->
<div class="c3-banner">
  <div class="c-banner1">
    <div>
      <p class="c-t1">COOK</p>
      <p class="c-t2">요리는 소중한 추억을 만들어줍니다</p>
      <p class="c-t2">음식은 사람들을 함께 모으는 힘이 있습니다.</p>
    </div>
    <img src="https://cdn-icons-png.flaticon.com/512/985/985478.png?w=1060&t=st=1686644496~exp=1686645096~hmac=2400acefd5466edb39a6db31c274b13b24fcdd8f2b01d12e53a0ab0857f40b16" alt="배너" class="c-banner-img">
  </div>
</div>  {% endcomment %}


{% comment %} <div class="carousel_container">
  <div class="carousel">
    <div class="slides">
      <div class="slide w-100">
        <div class="c1-banner">
          <div class="c-banner1">
            <div>
              <p class="c-t1">STUDY</p>
              <p class="c-t2">글쓰기는 자기 발견과 성장의 기회입니다.</p>
              <p class="c-t2">매일 조금씩 나아지는 모습이 나의 진정한 성공입니다.</p>
            </div>
            <img src="https://www.nicetomeetme.kr/images/main/store_icon.png" alt="배너" class="c-banner-img">
          </div>
        </div>
      </div>
      <div class="slide w-100">
        <div class="c2-banner">
          <div class="c-banner1">
          <div>
            <p class="c-t1">ACTIVITY</p>
            <p class="c-t2">스포츠는 몸과 마음을 강화하는 길입니다.</p>
            <p class="c-t2">운동은 스트레스를 해소하고 자신감을 키우는 방법입니다.</p>
          </div>
          <img src="https://cdn-icons-png.flaticon.com/512/901/901788.png?w=1060&t=st=1686644544~exp=1686645144~hmac=2fe3408d80af5f22a259548b6d3e7056237fa3f735e1cf3fd42bd40f78e5c687" alt="배너" class="c-banner-img">
        </div>
      </div>
      </div>
      <div class="slide w-100">
        <div class="c3-banner">
          <div class="c-banner1">
          <div>
            <p class="c-t1">COOK</p>
            <p class="c-t2">요리는 소중한 추억을 만들어줍니다</p>
            <p class="c-t2">음식은 사람들을 함께 모으는 힘이 있습니다.</p>
          </div>
        <img src="https://cdn-icons-png.flaticon.com/512/985/985478.png?w=1060&t=st=1686644496~exp=1686645096~hmac=2400acefd5466edb39a6db31c274b13b24fcdd8f2b01d12e53a0ab0857f40b16" alt="배너" class="c-banner-img">
      </div>
    </div>
      </div>
    </div>
    <button class="prev-button">&lt;</button>
    <button class="next-button">&gt;</button>
    <div class="dots">
      <button class="dot"></button>
      <button class="dot"></button>
      <button class="dot"></button>
    </div>
  </div>
</div>  {% endcomment %}




<!-- 배너 -->
<div class="banner">
  <div class="banner1">
    <div>
    <p class="t1">자신을 사랑하고 자신을 돌봐 주세요.</p>
    <p class="t2">행복은 마음의 상태에서 비롯됩니다. 내 안에서 평화를 찾고, 그 안에서 행복을 발견하세요</p>
    </div>
  <img src="{% static 'img/trees.png' %}" alt="배너" class="banner-img">
  </div>
</div>  


{% endblock content %} 


{% block script %}
 <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/index.js' %}"></script> 
<script src="{% static 'js/carousel.js' %}"></script>

{% endblock script %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="https://cdn.discordapp.com/attachments/1052099940475748403/1118867906302857246/logo1-2.png"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    {% block link %}{% endblock link %}
    <title>{% block title %}{% endblock title %}</title>
    {% block style %}{% endblock style %}
  </head>
  <body class="d-flex flex-column h-100">
    <nav>{% include "navbar.html" %}</nav>
    
  <main class="flex-shrink-0">
        {% block content %}{% endblock content %}
  </main>

    {% include "footer.html" %}
      
  </body>
  {% block script %}{% endblock script %}
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"
  ></script>

   <!-- Channel Plugin Scripts -->
   <script>
    (function(){var w=window;if(w.ChannelIO){return w.console.error("ChannelIO script included twice.");}var ch=function(){ch.c(arguments);};ch.q=[];ch.c=function(args){ch.q.push(args);};w.ChannelIO=ch;function l(){if(w.ChannelIOInitialized){return;}w.ChannelIOInitialized=true;var s=document.createElement("script");s.type="text/javascript";s.async=true;s.src="https://cdn.channel.io/plugin/ch-plugin-web.js";var x=document.getElementsByTagName("script")[0];if(x.parentNode){x.parentNode.insertBefore(s,x);}}if(document.readyState==="complete"){l();}else{w.addEventListener("DOMContentLoaded",l);w.addEventListener("load",l);}})();
  
    ChannelIO('boot', {
      "pluginKey": "e9460f81-7a6f-442d-8f93-23a70f8e892b"
    });
    </script>
        <!-- End Channel Plugin -->
</html>

templates/footer.html
{% load static %} 

{% block title %}{% endblock title %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/footer.css' %}" />
{% endblock head %}
{% block content %}

    <div class="container-md">
      <div class="row d-flex flex-wrap-reverse">
        <div class="col-12 col-lg-6 gap-1 mb-5 mt-lg-5">
          <img class="d-block" src="https://cdn.discordapp.com/attachments/1100972477645078538/1116235193225850920/logo1-2.png" alt="Logo" width="120" height="33">
            HobbyHub &copy; 2023 team 1.
            <a href="https://github.com/HobbyHub-1/HobbyHub" class="text-light text-decoration-none">HobbyHub</a>
          <div>multi-campus KDT 2th final-project</div>
          <div>
            <a class="text-decoration-none text-secondary" href="https://github.com/doll2gom">김신혜</a>
            <a class="text-decoration-none text-secondary" href="https://github.com/juunhyuukk">권준혁</a>
            <a class="text-decoration-none text-secondary" href="https://github.com/zzgh06">최충현</a>
            <a class="text-decoration-none text-secondary" href="https://github.com/nihelv">추연선</a>
            <a class="text-decoration-none text-secondary" href="https://github.com/jihye1662">임지혜</a>
          </div>
        </div>
        <div class="col-12 col-lg-6 gap-3 my-5">
          <div class="row">
            <div class="col-3 gap-2">
              <div>서비스 소개</div>
              <div>문의하기</div>
              <div>공지사항</div>
            </div>
            <div class="col-3 gap-2">
              <div>서비스 소개</div>
              <div>문의하기</div>
            </div>
          </div>
        </div>

      </div>
    </div>

{% endblock content %} 

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>
{% endblock script %}

templates/navbar.html
{% load static %} {% block link %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}" />
{% endblock link %} {% block title %}{% endblock title %} 
{% block style %}{% endblock style %} {% block content %}

<header>
  <nav class="navbar navbar-expand-lg fixed-top" id="nav">
    <div class="container-lg">
      <!-- 로고 -->
      <a href="{% url 'posts:index' %}">
        <img src="https://media.discordapp.net/attachments/1100972477645078538/1116235193481707570/logo1_2.png?width=330&height=91" alt="Logo" width="120" height="33">
      </a>         
      <!-- 메뉴바 -->
      <nav>
        <div class="left-nav-links">
          <!--메인-->
          <div>
            <a href="{% url 'posts:index'  %}">
              <img src="https://cdn-icons-png.flaticon.com/512/747/747420.png?w=1060&t=st=1686239776~exp=1686240376~hmac=b401c9220dcb430373a24cac4726f4644cc66723b27d3fcfa120e1558e31dc93" alt="메인" width="26" height="26">
            </a>
            <a href="{% url 'posts:index'  %}">
              <span>메인</span>
            </a>
          </div>
          <!--그룹-->
          <div>
            <a href="{% url 'posts:group_list'  %}">
              <img src="https://cdn-icons-png.flaticon.com/512/1243/1243615.png?w=1060&t=st=1686239874~exp=1686240474~hmac=cded211e818fe7317707a12f3c03afb2f343b5d9828af2278ea4409e7e64f026" alt="그룹" width="26" height="26">
            </a>
            <a href="{% url 'posts:group_list'  %}">
              <span>그룹</span>
            </a>
          </div>
          <!--위치-->
          <div>
            <a href="{% url 'posts:where' %}">
              <img src="https://cdn-icons-png.flaticon.com/512/286/286036.png?w=1060&t=st=1686239922~exp=1686240522~hmac=901bdbaf8df7a455e884f011bc9cdb01c25d07d42b6081e0121df9d1c5049bd2" alt="위치" width="26" height="26">
            </a>
            <a href="{% url 'posts:where'  %}">
              <span>위치</span>
            </a>
          </div>
          <!--마이페이지-->
          <div>
            {% if request.user.is_authenticated %}
                <a href="{% url 'accounts:profile' user.username %}">
                  <img src="https://cdn-icons-png.flaticon.com/512/118/118174.png?w=1060&t=st=1686242538~exp=1686243138~hmac=38367ddfd5ff490fea21a75b9c6be909eff31b0a8be3ac1f8da3074e855209aa" alt="마이페이지" width="26" height="26">
                </a>
                <a href="{% url 'accounts:profile' user.username %}">
                <span>마이페이지</span>
                </a>
            {% else %}
                <a href="{% url 'accounts:login' %}">
                  <img src="https://cdn-icons-png.flaticon.com/512/118/118174.png?w=1060&t=st=1686242538~exp=1686243138~hmac=38367ddfd5ff490fea21a75b9c6be909eff31b0a8be3ac1f8da3074e855209aa" alt="마이페이지" width="26" height="26">
                </a>
                <a href="{% url 'accounts:login' %}">
                  <span>마이페이지</span>
                </a>
            {% endif %}
          </div>
        </div>
      </nav>        
      <!-- 로그인 및 회원가입 -->
      <div class="menu-links">
        {% if request.user.is_authenticated %}
          <!-- 인증된 사용자 메뉴 -->   
          {% comment %} <a href="{% url  'accounts:profile' user.username  %}">프로필</a> {% endcomment %}
          {% comment %} <a href="{% url 'accounts:update' %}">회원정보수정</a> {% endcomment %}
          <a href="{% url 'accounts:logout' %}" class="text-decoration-none text-secondary login-Btn">Logout</a> 
        {% else %}
          <!-- 비인증 사용자 메뉴 -->
          <a type="button" href="{% url 'accounts:login' %}" class="text-decoration-none text-secondary login-Btn">Login</a>
          <a type="button" href="{% url 'accounts:signup' %}" class="text-decoration-none text-secondary login-Btn">Sign up</a>
        {% endif %}
      </div>
    </div>
  </nav>
</header> 


{% endblock content %}{% block script %}

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>

{% endblock script %} 

templates/subdivision.html
{% load static %} 

{% block title %}{% endblock title %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/subdivision.css' %}" />
{% endblock head %}
{% block content %}

 <div class="menu">
  <ul class="menu-list">
    <div class="menu-item">
      <a href="{% url 'posts:category' 'sports' %}">
              <img src="https://cdn-icons-png.flaticon.com/512/649/649420.png?w=1060&t=st=1686287270~exp=1686287870~hmac=1a0b18a19c3bcaf6639b387273aba7df54794ff1a488f17c59285f589ddc19de" alt="운동·스포츠" width="70" height="70">
            </a>    
    <span>운동·스포츠</span>
    </div>
    <div class="menu-item">
      <a href="{% url 'posts:category' 'diy' %}">
              <img src="https://cdn-icons-png.flaticon.com/512/639/639164.png?w=1060&t=st=1686291075~exp=1686291675~hmac=c1a4be2feda760a3f2831d69ecdc1905b27649414d69b2755113d70233e7f0ad" alt="DIY 공예" width="70" height="70">
            </a>    
    <span>DIY 공예</span>
    </div>
    <div class="menu-item">
      <a href="{% url 'posts:category' 'reading study' %}">
              <img src="https://cdn-icons-png.flaticon.com/512/767/767956.png?w=1060&t=st=1686290254~exp=1686290854~hmac=925b7e9bc2e1c99d30b2412536184ac8352b94b7d9d0ea5c88a5d3955ae4a322" alt="독서·공부" width="70" height="70">
            </a>    
    <span>독서·공부</span>
    </div>
    <div class="menu-item">
      <a href="{% url 'posts:category' 'art music movie' %}">
              <img src="https://cdn-icons-png.flaticon.com/512/808/808503.png?w=1060&t=st=1686290316~exp=1686290916~hmac=b411161611518012dc75446685e466914b62f2de73ba5fa0ce4497b1599f4fb2" alt="미술·음악·영화" width="70" height="70">
            </a>    
    <span>미술·음악·영화</span>
    </div>
    <div class="menu-item">
      <a href="{% url 'posts:category' 'cultural activities' %}">
              <img src="https://cdn-icons-png.flaticon.com/512/991/991920.png?w=1060&t=st=1686291182~exp=1686291782~hmac=b466fb122dbd7ffb9b8c177974d9e8dca4755fdbab34cd6c5c37f1b75ea600dd" alt="문화활동" width="70" height="70">
            </a>    
    <span>문화활동</span>
    </div>
    <div class="menu-item">
      <a href="{% url 'posts:category' 'cook' %}">
              <img src="https://cdn-icons-png.flaticon.com/512/1249/1249623.png?w=1060&t=st=1686290773~exp=1686291373~hmac=d5f5deb6996588362640774b5d3f9c5a621b64f1c18858f6f9327cf085f3e1f2" alt="요리" width="70" height="70">
            </a>    
    <span>요리</span>
    </div>
    <div class="menu-item">
      <a href="{% url 'posts:category' 'healing' %}">
              <img src="https://cdn-icons-png.flaticon.com/512/390/390754.png?w=1060&t=st=1686290929~exp=1686291529~hmac=f27b04674b95ed3c35476672f0656f4e0af95c02f1dff497aadce81b46188d59" alt="힐링" width="70" height="70">
            </a>    
    <span>힐링</span>
    </div>
  </ul>
</div> 

    {% endblock content %} 

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>
{% endblock script %}

templates/subdivision_g.html
{% load static %} 

{% block title %}{% endblock title %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/subdivision.css' %}" />
{% endblock head %}
{% block content %}

 <div class="menu">
  <ul class="menu-list">
    <div class="menu-item">
      <a href="/posts/group/?category=운동+스포츠">
        <img src="https://cdn-icons-png.flaticon.com/512/649/649420.png?w=1060&t=st=1686287270~exp=1686287870~hmac=1a0b18a19c3bcaf6639b387273aba7df54794ff1a488f17c59285f589ddc19de" alt="운동·스포츠" width="70" height="70">
      </a>
      <span>운동·스포츠</span>
    </div>
    <div class="menu-item">
      <a href="/posts/group/?category=DIY+공예">
              <img src="https://cdn-icons-png.flaticon.com/512/639/639164.png?w=1060&t=st=1686291075~exp=1686291675~hmac=c1a4be2feda760a3f2831d69ecdc1905b27649414d69b2755113d70233e7f0ad" alt="DIY 공예" width="70" height="70">
            </a>    
    <span>DIY 공예</span>
    </div>
    <div class="menu-item">
      <a href="/posts/group/?category=독서+공부">
              <img src="https://cdn-icons-png.flaticon.com/512/767/767956.png?w=1060&t=st=1686290254~exp=1686290854~hmac=925b7e9bc2e1c99d30b2412536184ac8352b94b7d9d0ea5c88a5d3955ae4a322" alt="독서·공부" width="70" height="70">
            </a>    
    <span>독서·공부</span>
    </div>
    <div class="menu-item">
      <a href="/posts/group/?category=미술+음악+영화">
              <img src="https://cdn-icons-png.flaticon.com/512/808/808503.png?w=1060&t=st=1686290316~exp=1686290916~hmac=b411161611518012dc75446685e466914b62f2de73ba5fa0ce4497b1599f4fb2" alt="미술·음악·영화" width="70" height="70">
            </a>    
    <span>미술·음악·영화</span>
    </div>
    <div class="menu-item">
      <a href="/posts/group/?category=문화활동">
              <img src="https://cdn-icons-png.flaticon.com/512/991/991920.png?w=1060&t=st=1686291182~exp=1686291782~hmac=b466fb122dbd7ffb9b8c177974d9e8dca4755fdbab34cd6c5c37f1b75ea600dd" alt="문화활동" width="70" height="70">
            </a>    
    <span>문화활동</span>
    </div>
    <div class="menu-item">
      <a href="/posts/group/?category=요리">
              <img src="https://cdn-icons-png.flaticon.com/512/1249/1249623.png?w=1060&t=st=1686290773~exp=1686291373~hmac=d5f5deb6996588362640774b5d3f9c5a621b64f1c18858f6f9327cf085f3e1f2" alt="요리" width="70" height="70">
            </a>    
    <span>요리</span>
    </div>
    <div class="menu-item">
      <a href="/posts/group/?category=힐링">
              <img src="https://cdn-icons-png.flaticon.com/512/390/390754.png?w=1060&t=st=1686290929~exp=1686291529~hmac=f27b04674b95ed3c35476672f0656f4e0af95c02f1dff497aadce81b46188d59" alt="힐링" width="70" height="70">
            </a>    
    <span>힐링</span>
    </div>
  </ul>
</div> 

    {% endblock content %} 

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>
{% endblock script %}