chats/urls.py
from django.urls import path
from . import views

app_name = 'chats'
urlpatterns = [
    path('inbox/', views.inbox, name='inbox'),
    path('<int:user_id>/', views.start_chat, name='start_chat'),
    path('start_group_chat/', views.start_group_chat, name='start_group_chat'),
    path('<str:room_name>/', views.room, name='room'),
    path('<str:room_name>/delete/', views.delete_chat, name='delete_chat'),
    path('api/unread_notifications/', views.unread_notifications, name='unread_notifications'),
    path('api/new_chat_rooms/', views.get_new_chat_rooms, name='new_chat_rooms'),
]

config/urls.py
#config/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
    path('chat/', include('chat.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # post
    path('', views.index, name='index'),
    # path('posts/hobby/', views.hobby, name='hobby'),
    path('posts/<int:post_pk>/', views.post_detail, name='post_detail'),
    path('posts/create/', views.post_create, name='post_create'),
    path('posts/<int:post_pk>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_pk>/update/', views.post_update, name='post_update'),
    path('posts/<int:post_pk>/comments/', views.post_comments_create, name='post_comments_create'),
    path('posts/<int:post_pk>/comments/<int:comment_pk>/delete', views.post_comments_delete, name='post_comments_delete'),
    # path('posts/<int:post_pk>/comments/<int:comment_pk>/update', views.post_comments_update, name='post_comments_update'),
    path('posts/<int:post_pk>/post_likes/', views.post_likes, name='post_likes'),
    path('posts/where', views.where, name='where'),

    # group
    path('posts/group/', views.group_list, name='group_list'),
    path('posts/group/<int:group_pk>/', views.group_detail, name='group_detail'),
    path('posts/group/create/', views.group_create, name='group_create'),
    path('posts/group/<int:group_pk>/update/', views.group_update, name='group_update'),
    path('posts/group/<int:group_pk>/delete/', views.group_delete, name='group_delete'),
    path('posts/group/<int:group_pk>/comments/', views.group_comments_create, name='group_comments_create'),
    path('posts/group/<int:group_pk>/comments/<int:comment_pk>/delete', views.group_comments_delete, name='group_comments_delete'),
    # path('posts/group/<int:group_pk>/comments/<int:comment_pk>/update/', views.group_comments_update, name='group_comments_update'),
    path('posts/group/<int:group_pk>/group_likes/', views.group_likes, name='group_likes'),

    # 기타
    path('posts/search/', views.search, name='search'),
    path('posts/category/<str:subject>/', views.category, name='category'),
    # path('posts/guide/', views.guide, name='guide'),
]   

posts/models.py
#posts/models.py

from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from taggit.managers import TaggableManager
from django.utils import timezone
from datetime import timedelta,datetime
# from django.core.validators import RegexValidator
# from django.core.validators import MinValueValidator, MaxValueValidator
import os

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=100, default='')
    content = models.CharField(max_length=100000)
    hits = models.PositiveIntegerField(default=0)
    category = models.CharField(max_length=20)
    tags = TaggableManager(blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    

class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = ProcessedImageField(upload_to='hobby', blank=True,
                                processors=[ResizeToFill(400,400)],
                                format='JPEG',
                                options={'quality': 100})


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False


class Group(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_group')
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=100, default='')
    address = models.CharField(max_length=200)
    content = models.CharField(max_length=2000)
    hits = models.PositiveIntegerField(default=0)

    day_choices = (('월요일', '월요일'), ('화요일', '화요일'), ('수요일', '수요일'), ('목요일', '목요일'), ('금요일', '금요일'), ('토요일', '토요일'), ('일요일', '일요일'))
    day = models.CharField(max_length=10, choices=day_choices)
    
    region_choices = (('서울', '서울'), ('인천', '인천'), ('경기도', '경기도'), ('강원도', '강원도'), 
                      ('경남', '경남'), ('경북', '경북'), ('전남', '전남'), ('전북', '전북'), ('충남', '충남'), ('충북', '충북'))
    region = models.CharField(max_length=20, choices=region_choices)

    gender_choices = (('남/여', '남/여'), ('남', '남'), ('여', '여'))
    gender = models.CharField(max_length=10, choices=gender_choices)
    
    propensity_choices = (('활동적', '활동적'), ('비활동적', '비활동적'))
    propensity = models.CharField(max_length=10, choices=propensity_choices, null=True)
    
    category_choices = (('운동 스포츠', '운동 스포츠'), ('DIY 공예', 'DIY 공예'), ('독서 공부', '독서 공부'), ('미술 음악 영화','미술 음악 영화'), ('힐링', '힐링'), ('요리', '요리'), ('문화 활동', '문화 활동'))
    category = models.CharField(max_length=20, choices=category_choices)
    
    tags = TaggableManager(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
   
    def __str__(self):
        return self.title
    
    
# class Category(models.Model):
#    name = models.CharField(max_length=100)

 #   def __str__(self):
  #      return self.name


class GroupImage(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    image = ProcessedImageField(upload_to='group', blank=True,
                                processors=[ResizeToFill(400,400)],
                                format='JPEG',
                                options={'quality': 100})
    

class GroupComment(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=300)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def created_string(self):
        if self.created_at is None:
            return False

        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + '일 전'
        else:
            return False

posts/forms.py
from django import forms
from .models import Post, PostImage, PostComment, Group, GroupImage, GroupComment
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django_summernote.fields import SummernoteTextFormField, SummernoteTextField

class PostForm(forms.ModelForm):
    title = forms.CharField(label='',
        widget = forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': '제목을 입력하세요',
               'autofocus': True,}),)
    subtitle = forms.CharField(label='',
        widget = forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': '소제목을 입력하세요',}),)
    category = forms.ChoiceField(label='', 
        choices=Group.category_choices, 
        widget=forms.Select(attrs={'class': 'form-select'}),)
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['tags'].label = ''
        self.fields['tags'].widget.attrs.update({
            'placeholder': '태그를 입력해주세요.',
            'class': 'form-control',}),
    class Meta:
        model = Post
        fields = ( 'title','subtitle', 'category', 'content',  'tags',)
        widgets = {'content': SummernoteWidget(),}

class PostImageFrom(forms.ModelForm):
    image = forms.ImageField(
        label='대표이미지는 3장까지 업로드', 
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control', 
                'multiple': True,
                },
            ), required=False,
    )

    class Meta:
        model = PostImage
        fields = ('image',)


class PostCommentForm(forms.ModelForm):
    content = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': '댓글을 입력하세요', }))
    class Meta:
        model = PostComment
        fields = ( 'content',)


class GroupForm(forms.ModelForm):
    title = forms.CharField(label='',
        widget = forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': '제목을 입력하세요',
                'autofocus': True,}),)
    subtitle = forms.CharField(label='',
        widget = forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': '소제목을 입력하세요',}),)
    category = forms.ChoiceField(label='카테고리', 
        choices=Group.category_choices, 
        widget=forms.Select(attrs={'class': 'form-select'}),)
    gender = forms.ChoiceField(label='', 
        choices=Group.gender_choices, 
        widget=forms.Select(attrs={'class': 'form-select'}),)
    propensity = forms.ChoiceField(label='',
        choices=Group.propensity_choices, 
        widget=forms.Select(attrs={'class': 'form-select'}),)
    day = forms.ChoiceField(label='요일', 
        choices=Group.day_choices, 
        widget=forms.Select(attrs={'class': 'form-select', }),)
    region = forms.ChoiceField(label='', 
        choices=Group.region_choices, 
        widget=forms.Select(attrs={'class': 'form-select'}),)
    address = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': '주소를 입력하세요',}))
    
    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)
        self.fields['tags'].label = ''
        self.fields['tags'].widget.attrs.update({
            'placeholder': '태그를 입력하세요. ',
            'class': 'form-control',})
    class Meta:
        model = Group
        fields = ('title', 'subtitle','category', 'day','gender', 'propensity',  'region', 'address', 'content','tags',)
        widgets = {'content': SummernoteWidget(),}


class GroupImageFrom(forms.ModelForm):
    image = forms.ImageField(
        label='',
        widget=forms.ClearableFileInput(attrs={'class': 'form-control', 'multiple': True}),
        required=False
    )

    class Meta:
        model = GroupImage
        fields = ('image',)


class GroupCommentForm(forms.ModelForm):
    content = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': '댓글을 입력하세요', }))
    class Meta:
        model = GroupComment
        fields = ( 'content',)
        

posts/templates/posts/group_detail.html
{% extends 'base.html' %}
{% load static %}
{% block link %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static 'css/group_detail.css' %}">
{% endblock link %}
{% block title %}Group{% endblock title %}
{% block content %}
<div class="container-md">

<!-- ## 화면 상단 케로젤+정보 ## -->
  <div class="row mt-5">
    <!-- 케로젤 이미지 -->
    <div class="carousel col-lg-8 h-auto p-0">
      <div class="slides w-100 h-auto">
          <!-- 그룹 이미지 표시 -->
        {% for group_image in group_images %}
          <img class="slide w-100" id="object-position-1" src="{{ group_image.image.url }}" alt="group_carousel_img">
        {% endfor %}
      </div>
      <button class="prev-button">&lt;</button>
      <button class="next-button">&gt;</button>
      <div class="dots">
        <button class="dot"></button>
        <button class="dot"></button>
        <button class="dot"></button>
      </div>
    </div>

    <!-- 주요 정보 -->
    <div class="post_info col col-lg-4">
      <span class="category">{{ group.get_category_display }}</span>
      <h2 class="title">{{ group.title }}</h2>
      <h5 class="subtitle">{{ group.subtitle }}</h5>

      <!-- 그룹 작성자 프로필 -->
      <div class="user justify-content-center my-4">
        {% if group.user.profile_image %}
          <img class="rounded-circle me-2" src="{{ group.user.profile_image.url }}" width="30px" alt="Profile Image">
        {% else %}
          <img class="rounded-circle me-2" src="https://i.postimg.cc/kXwSg0M2/image.jpg" width="30px" alt="Default Profile Image">
        {% endif %}
        {{ group.user }}
      </div>

      <hr style="color: rgb(238, 128, 65);">

      <div class="mt-4 icons">
        <p class="day">
          <i class="bi bi-calendar-check-fill me-2"></i>
           <strong class="pe-3">요일</strong>{{ group.day }}
        </p>
          <p class="address">
            <i class="bi bi-geo-alt-fill me-2"></i>
            <strong class="pe-3">위치</strong>{{ group.address }}
          </p>
        <p class="tags">
          <i class="bi bi-tags-fill me-2"></i>
          {% for tag in group.tags.all %} 
            #{{ tag }} 
            {% empty %}
            #{{ group.get_category_display }}
          {% endfor %}
        </p>
        <p class="hits">
          <i class="bi bi-eye-fill me-2"></i>
          {{ group.hits }}
        </p>
        <!-- 좋아요 -->
        <div class="my-1">
          {% if request.user.is_authenticated %}
            <form id="group-likes-form" data-group-id="{{ group.pk }}">
              {% csrf_token %}
              {% if request.user in group.like_users.all %}
                <button class="likebtn mb-2 align-content-center"  type="submit">
                  <i class="me-2 bi bi-heart-fill" id="group-heart"></i>
                  <span id="like-count">
                    {{ group.like_users.all|length }}
                  </span>
                </button>
              {% else %}
                <button class="likebtn mb-2 align-content-center"  type="submit">
                  <i class="me-2 bi bi-heart" id="group-heart"></i>
                  <span id="like-count">
                    {{ group.like_users.all|length }}
                  </span>
                </button>
              {% endif %}
            </form>
          {% else %}
            <button class="likebtn mb-2 align-content-center"  type="submit">
              <i class="me-2 bi bi-heart" id="group-heart"></i>
              <span id="like-count">
                {{ group.like_users.all|length }}
              </span>
            </button>
          {% endif %}
        </div>
      </div>

      <!-- 대표 이미지 나열 -->
      <div class="container-md post_detail_content my-4">
        {% for group_image in group_images %}
          <img class="col" width="100" src="{{ group_image.image.url }}" alt="Group Image">
        {% endfor %}
      </div>

      <!-- 삭제 수정 목록보기 : 버튼 -->
      <div class="my-2 text-end buttons">
        {% if request.user == group.user %}
          <button class="btn btn-custom btn-sm d-inline" data-bs-toggle="modal" data-bs-target="#deleteModal">삭제</button>
          <a class="btn btn-custom btn-sm" href="{% url 'posts:group_update' group.pk %}"><i class="bi bi-pencil-square"></i>수정하기</a>
        {% endif %}
        <!-- 완성후 목록보기 버튼은 삭제할 예정입니다. -->
        <a class="btn btn-custom btn-sm" href="{% url 'posts:group_list' %}">목록보기</a>
      </div>

    </div>
  </div>
  
<!--## navigation bar : 상세내용 + 댓글  ##-->
  <div class="mt-4 d-flex justify-content-center">
    <div class="col-11">
      <ul class="nav nav-underline">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#info">모임 소개</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" href="#comment">참여 후기</a>
        </li>
      </ul>

<!-- ## 상세 내용 ## -->
      <div class="content">
        <p class="">{{ group.content | safe }}</p>
      </div>

      <!-- 위로가기 Top -->
      <div class="my-5 d-flex justify-content-center">
        <a href="#" class="btn btn-custom">Top</a>
      </div>

<!-- ## 댓글 ## -->
      <div class="comments" id="comment">
        <h5>실제 참여후기</h5>

        <hr style="color: rgb(238, 128, 65);">

        {% for comment in group_comments %}
          <div class="position-relative comment mx-3 my-3">
            <p class="d-inline text-muted comment_info ">
              {{ comment.user }} {{ comment.created_string }}
            </p>
            <!-- 댓글 삭제 -->
            {% if request.user == comment.user %}
              <form class="position-absolute bottom-0 end-0" action="{% url 'posts:group_comments_delete' group.pk comment.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="btn btn-custom btn-sm" value="삭제">
              </form>
            {% endif %}
            <p>{{ comment.content }}</p>
          </div>
        {% endfor %}

        <!-- 댓글 작성창 -->
        <form class="mt-4 row justify-content-center w-100 m-0" action="{% url 'posts:group_comments_create' group.pk  %}" method="POST">
          {% csrf_token %}
          <div class="col">
            {{ group_comment_form.content }}
          </div>
          <input class="col-2 col-lg-1 btn btn-custom" type="submit" value="리뷰 작성">
        </form>
      </div>

    </div>
  </div>

</div>

<!-- 삭제 모달 -->
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">그룹 삭제 확인</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>그룹을 삭제하시겠습니까?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">아니오</button>
          <form class="d-inline" action="{% url 'posts:group_delete' group.pk  %}" method="POST">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="예">
          </form>
        </div>
      </div>
    </div>
  </div>


{% endblock content %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/carousel.js' %}"></script>
<script src="{% static 'js/group_detail.js' %}"></script>
{% endblock script %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block link %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static 'css/group_detail.css' %}">
{% endblock link %}
{% block title %}post_detail{% endblock title %}
{% block content %}
<div class="container-md">

<!-- ## 화면 상단 케로젤+정보 ## -->
  <div class="row my-5">
    <!-- 케로젤 이미지 -->
    <div class="carousel col-lg-8 h-auto p-0">
      <div class="slides w-100 h-auto">
        {% for image in post_images %}
          <img class="slide w-100" id="object-position-1" src="{{ image.image.url }}" alt="post_carousel_img">
        {% endfor %}
      </div>
      <button class="prev-button">&lt;</button>
      <button class="next-button">&gt;</button>
      <div class="dots">
        <button class="dot"></button>
        <button class="dot"></button>
        <button class="dot"></button>
      </div>
    </div>

    <!-- 주요 정보 -->
    <div class="post_info col col-lg-4">
      <span class="category">{{ post.category }}</span>
      <h2 class="title">{{ post.title }}</h2>
      <div class="user justify-content-center my-4"></div>

      <hr style="color: rgb(238, 128, 65);">
      
      <h5 class="subtitle">{{ post.subtitle }}</h5>
      <div class="mt-4 icons">
        <p class="tags">
          <i class="bi bi-tags-fill me-2"></i>
          {% for tag in post.tags.all %}
            #{{ tag }}
            {% empty %}
            #{{ post.category }}
          {% endfor %}
        </p>
        <p class="hits my-2">
          <i class="bi bi-eye-fill me-2"></i>
          {{ post.hits }}
        </p>
      </div>
      
      <!-- 대표 이미지 나열 -->
      <div class="container-md post_detail_content my-4">
        {% for image in post_images %}
          <img class="col" width="100" src="{{ image.image.url }}" alt="Post Image">
        {% endfor %}
      </div>

      <!-- 삭제 수정 목록보기 : 버튼 -->
      <div class="my-2 text-end buttons">
        {% if request.user == post.user %}
          <button class="btn btn-custom btn-sm d-inline" data-bs-toggle="modal" data-bs-target="#deleteModal">삭제</button>
          <a class="btn btn-custom btn-sm" href="{% url 'posts:post_update' post.pk %}"><i class="bi bi-pencil-square"></i>수정하기</a>
        {% endif %}
        <!-- 완성후 목록보기 버튼은 삭제할 예정입니다. -->
        <a class="btn btn-custom btn-sm" href="{% url 'posts:index' %}">목록보기</a>
      </div>

    </div>
  </div>
  
<!--## navigation bar : 상세내용 + 댓글 ##-->
  <div class="mt-4 d-flex justify-content-center">
    <div class="col-11">
      <ul class="nav nav-underline">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#info">취미 소개</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" href="#comment">comment</a>
        </li>
      </ul>

<!-- ## 상세 내용 ## -->
      <div class="content">
        <p class="">{{ post.content | safe }}</p>
      </div>

      <!-- 위로가기 Top -->
      <div class="my-5 d-flex justify-content-center">
        <a href="#" class="btn btn-custom">Top</a>
      </div>

<!-- ## 댓글 ## -->
      <div class="comments" id="comment">
        <h4>댓글</h4>

        <hr style="color: rgb(238, 128, 65);">

        {% for comment in post_comments %}
          <div class="position-relative comment mx-3 my-3">
            <p class="d-inline text-muted comment_info">
              {{ comment.user }} {{ comment.created_string }}
            </p>
            <!-- 댓글 삭제 -->
            {% if request.user == comment.user %}
              <form class="position-absolute bottom-0 end-0" action="{% url 'posts:post_comments_delete' post.pk comment.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="btn btn-custom btn-sm" value="삭제">
              </form>
            {% endif %}
            <p>{{ comment.content }}</p>
          </div>
        {% endfor %}

        <!-- 댓글 작성창 -->
        <form class="mt-4 row justify-content-center w-100 m-0" action="{% url 'posts:post_comments_create' post.pk %}" method="POST">
          {% csrf_token %}
          <div class="col">
            {{ post_comment_form.content }}
          </div>
          <input class="col-2 col-lg-1 btn btn-custom" type="submit" value="댓글 작성">
        </form>
      </div>

    </div>
  </div>

</div>

<!-- 삭제 모달 -->
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">게시물 삭제</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>게시물을 삭제하시겠습니까?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">아니오</button>
          <form class="d-inline" action="{% url 'posts:post_delete' post.pk  %}" method="POST">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="예">
          </form>
        </div>
      </div>
    </div>
  </div>

  {% endblock content %}
{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="{% static 'js/carousel.js' %}"></script>
{% endblock script %}